version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/templates/service"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "node"
        versions: ["15.x.x-alpine", "16.x.x-alpine"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "impact/no-changelog-required"
      - "github_actions"
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/templates/service"
    schedule:
      interval: "daily"
    labels:
      - "impact/no-changelog-required"
      - "github_actions"
      - "dependencies"
      - "templates/service"
  - package-ecosystem: "github-actions"
    directory: "/templates/monorepo-service"
    schedule:
      interval: "daily"
    labels:
      - "impact/no-changelog-required"
      - "github_actions"
      - "dependencies"
      - "templates/service"
  - package-ecosystem: "github-actions"
    directory: "/templates/infra"
    schedule:
      interval: "daily"
    labels:
      - "impact/no-changelog-required"
      - "github_actions"
      - "dependencies"
      - "templates/infra"
    