version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - indivorg/developers
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "typescript*"
      - dependency-name: "@types/node"
        versions: ["15.x"]
    labels:
      - impact/no-changelog-required
      - dependencies/javascript
      - kind/dependencies
    