name: Canary Release
on:
  push:
    branches:
      - main
      - master

jobs:
  up:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ github.repository.name }}
      IMAGE_NAME: eu.gcr.io/indiv-app/${{ github.repository.name }}
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_PROJECT_SA_KEY }}
          export_default_credentials: true

      - run: gcloud auth configure-docker

      - uses: actions/checkout@v2.3.4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Request version update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.INDIVBOT_GITHUB_TOKEN }}
          repository: indivorg/infra-core
          event-type: update_version
          client-payload: '{"service": "${{ env.SERVICE_NAME }}", "new_version": "${{ steps.meta.outputs.version }}"}'
