name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_PROJECT_SA_KEY }}
          export_default_credentials: true

      - run: gcloud auth configure-docker

      - uses: actions/checkout@v2.3.4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images:
            eu.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{
            github.event.repository.name }}
          tags: |
            type=sha,prefix={{branch}}-

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            NPM_TOKEN=${{ secrets.INDIVBOT_GITHUB_TOKEN }}

      - name: Request version update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.INDIVBOT_GITHUB_TOKEN }}
          repository: indivorg/infra-app
          event-type: update_version
          client-payload:
            '{"service": "${{ github.event.repository.name }}", "new_version":
            "${{ steps.meta.outputs.version }}"}'
