name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: canary-release
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with Google Cloud Platform
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_PROJECT_SA_KEY }}

      - run: gcloud auth configure-docker

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: eu.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{
            github.event.repository.name }}
          tags: |
            type=sha,prefix={{branch}}-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NPM_TOKEN=${{ secrets.INDIVBOT_GITHUB_TOKEN }}

      - name: Request version update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.INDIVBOT_GITHUB_TOKEN }}
          repository: indivorg/infra-app
          event-type: update_version
          client-payload:
            '{"service": "${{ github.event.repository.name }}", "new_version":
            "${{ steps.meta.outputs.version }}"}'
